name: Publish

on:
  push:
    tags:
      - v*

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel babel
      - name: Build package
        # Remove `compile_catalog` if the package has no translations.
        run: |
          python setup.py compile_catalog sdist bdist_wheel
      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          user: __token__
          # The token is provided by the inveniosoftware organization
          password: ${{ secrets.pypi_token }}
